import 'package:notes_application/models/product_class.dart';
import 'package:flutter/material.dart';

class DummyData {
  static List<Product> products = [
    Product(
        'GTX 1050',
        ['VRAM : 4GB'],
        'Me',
        [
          Image.asset('assets/images/product_images/gtx_1050.jpg'),
          Image.asset('assets/images/product_images/gtx_1050.jpg'),
          Image.asset('assets/images/product_images/gtx_1050.jpg'),
          Image.asset('assets/images/product_images/gtx_1050.jpg'),
        ],
        const AssetImage('assets/images/product_images/gtx_1050.jpg'),
        4.5,
        10,
        ['Very good product', 'Nice product', 'Great product']),
    Product(
        'GTX 1050ti',
        ['VRAM : 4GB'],
        'Me',
        [
          Image.asset('assets/images/product_images/gtx_1050ti.jpg'),
          Image.asset('assets/images/product_images/gtx_1050ti.jpg'),
          Image.asset('assets/images/product_images/gtx_1050ti.jpg'),
          Image.asset('assets/images/product_images/gtx_1050ti.jpg'),
        ],
        const AssetImage('assets/images/product_images/gtx_1050ti.jpg'),
        4.5,
        10,
        ['Very good product', 'Nice product', 'Great product']),
    Product(
        'GTX 1080',
        ['VRAM : 4GB'],
        'Me',
        [Image.asset('assets/images/product_images/gtx_1080.png')],
        const AssetImage('assets/images/product_images/gtx_1080.png'),
        4.5,
        10,
        ['Very good product', 'Nice product', 'Great product']),
    Product(
        'GTX 1080ti',
        ['VRAM : 4GB'],
        'Me',
        [Image.asset('assets/images/product_images/gtx_1080ti.png')],
        const AssetImage('assets/images/product_images/gtx_1080ti.png'),
        4.5,
        10,
        ['Very good product', 'Nice product', 'Great product']),
    Product(
        'GTX 1650',
        ['VRAM : 4GB'],
        'Me',
        [Image.asset('assets/images/product_images/gtx_1650.jpg')],
        const AssetImage('assets/images/product_images/gtx_1650.jpg'),
        4.5,
        10,
        ['Very good product', 'Nice product', 'Great product']),
    Product(
      'GTX 1660ti',
      ['VRAM : 4GB'],
      'Me',
      [Image.asset('assets/images/product_images/gtx_1660ti.jpg')],
      const AssetImage('assets/images/product_images/gtx_1660ti.jpg'),
      4.5,
      10,
      ['Very good product', 'Nice product', 'Great product'],
    ),
    Product(
      'GTX 1660ti',
      ['VRAM : 4GB'],
      'Me',
      [Image.asset('assets/images/product_images/gtx_1660ti.jpg')],
      const AssetImage('assets/images/product_images/gtx_1660ti.jpg'),
      4.5,
      10,
      ['Very good product', 'Nice product', 'Great product'],
    ),
    Product(
      'GTX 1660ti',
      ['VRAM : 4GB'],
      'Me',
      [Image.asset('assets/images/product_images/gtx_1660ti.jpg')],
      const AssetImage('assets/images/product_images/gtx_1660ti.jpg'),
      4.5,
      10,
      ['Very good product', 'Nice product', 'Great product'],
    ),
    Product(
      'GTX 1660ti',
      ['VRAM : 4GB'],
      'Me',
      [Image.asset('assets/images/product_images/gtx_1660ti.jpg')],
      const AssetImage('assets/images/product_images/gtx_1660ti.jpg'),
      4.5,
      10,
      ['Very good product', 'Nice product', 'Great product'],
    ),
  ];
}
